<?php
namespace Admin\Model;
use Think\Model\ViewModel;

class BloodtubeCateCaseViewModel extends ViewModel {
	public $viewFields = array(
		'BloodtubeCate' => array(
			'id',
			'case_id',
			'case_client_id',
			'used_time',
			'used_user_id',
			'is_used',
			'to_department_time',
			'to_department_user_id',
			'target_department_id',
			'is_to_department',
			'to_user_time',
			'to_user_user_id',
			'target_user_id',
			'is_to_user',
			'create_time',
			'create_user_id',
			'update_time',
			'update_user_id',
			'is_del',
			'_type' => 'LEFT',
		),
		'Bloodtube' => array(
			'id' => 'bloodtube_id',
			'bloodtube_cate_id' => 'bloodtube_cate_id',
			'code' => 'bloodtube_code',
			'recover_type' => 'bloodtube_recover_type',
			'recover_time' => 'bloodtube_recover_time',
			'recover_user_id' => 'bloodtube_recover_user_id',
			'is_recover' => 'bloodtube_is_recover',
			'is_del' => 'bloodtube_is_del',
			'_on' => 'BloodtubeCate.id=Bloodtube.bloodtube_cate_id',
			'_type' => 'LEFT',
		),
		'Cases' => array(
			'id' => 'case_table_id',
			'code' => 'case_code',
			'num' => 'case_num',
			'cate' => 'case_cate',
			'accident_name' => 'case_accident_name',
			'accident_time' => 'case_accident_time',
			'accident_place' => 'case_accident_place',
			'lng' => 'case_lng',
			'lat' => 'case_lat',
			'death_num' => 'case_death_num',
			'hurt_num' => 'case_hurt_num',
			'property_loss' => 'case_property_loss',
			'accident_type' => 'case_accident_type',
			'first_cognizance' => 'case_first_cognizance',
			'department_id' => 'case_department_id',
			'accept_status' => 'case_accept_status',
			'client_status' => 'case_client_status',
			'record_status' => 'case_record_status',
			'checkup_status' => 'case_checkup_status',
			'law_doc_status' => 'case_law_doc_status',
			'cognizance_status' => 'case_cognizance_status',
			'punish_status' => 'case_punish_status',
			'mediate_status' => 'case_mediate_status',
			'catalog_status' => 'case_catalog_status',
			'create_time' => 'case_create_time',
			'create_user_id' => 'case_create_user_id',
			'update_time' => 'case_update_time',
			'update_user_id' => 'case_update_user_id',
			'is_del' => 'case_is_del',
			'_table' => '__CASE__',
			'_type' => 'LEFT',
			'_on' => 'BloodtubeCate.case_id=Cases.id',
			'_type' => 'LEFT',
		),
		'Department' => array(
			'name' => 'department_name',
			'cate' => 'department_cate',
			'is_del' => 'department_is_del',
			'_on' => 'BloodtubeCate.target_department_id=Department.id',
			'_type' => 'LEFT',
		),
		'User' => array(
			'id' => 'user_id',
			'true_name' => 'true_name',
			'user_name' => 'user_name',
			'is_del' => 'user_is_del',
			'_on' => 'BloodtubeCate.target_user_id=User.id',
		),

	);
}
?>