<?php
namespace Admin\Model;
use Think\Model\ViewModel;

class CaseReviewViewModel extends ViewModel {
	public $viewFields = array(
		'CaseReview' => array(
			'id',
			'case_id',
			'case_code',
			'department_id',
			'handle_user_id',
			'handle_name',
			'accident_time',
			'accident_type',
			'apply_status',
			'apply_time',
			'accept_status',
			'accept_time',
			'check_status',
			'check_time',
			'stop_status',
			'stop_time',
			'create_time',
			'create_user_id',
			'update_time',
			'update_user_id',
			'is_over',
			'_type' => 'LEFT',
		),
		'CaseInfo' => array( // 案件
			'num' => 'case_num',
			'cate' => 'case_cate',
			'accident_name' => 'case_accident_name',
			'accident_time' => 'case_accident_time',
			'accident_place' => 'case_accident_place',
			'lng' => 'case_lng',
			'lat' => 'case_lat',
			'death_num' => 'case_death_num',
			'hurt_num' => 'case_hurt_num',
			'property_loss' => 'case_property_loss',
			'accident_type' => 'case_accident_type',
			'first_cognizance' => 'case_first_cognizance',
			'department_id' => 'case_department_id',
			'accept_status' => 'case_accept_status',
			'survey_status' => 'case_survey_status',
			'client_status' => 'case_client_status',
			'record_status' => 'case_record_status',
			'checkup_status' => 'case_checkup_status',
			'law_doc_status' => 'case_law_doc_status',
			'cognizance_status' => 'case_cognizance_status',
			'punish_status' => 'case_punish_status',
			'mediate_status' => 'case_mediate_status',
			'catalog_status' => 'case_catalog_status',
			'create_time' => 'case_create_time',
			'create_user_id' => 'case_create_user_id',
			'update_time' => 'case_update_time',
			'is_del' => 'case_is_del',
			'update_user_id' => 'case_update_user_id',
			'_table' => '__CASE__',
			'_on' => 'CaseReview.case_id=CaseInfo.id and CaseInfo.is_del=0',
			'_type' => 'LEFT',
		),
		'CaseHandle' => array( // 当前办案人
			'user_id' => 'case_handle_user_id',
			'start_time' => 'case_handle_start_time',
			'end_time' => 'case_handle_end_time',
			'is_now' => 'case_handle_is_now',
			'is_del' => 'case_handle_is_del',
			'_on' => 'CaseInfo.id=CaseHandle.case_id and CaseHandle.is_now=1 and CaseHandle.is_del=0',
			'_type' => 'LEFT',
		),
		'CaseHandleUser' => array( // 办案人信息
			'user_name' => 'case_handle_user_name',
			'true_name' => 'case_handle_true_name',
			'_table' => '__USER__',
			'_on' => 'CaseHandleUser.id=CaseHandle.user_id and CaseHandleUser.is_del=0',
			'_type' => 'LEFT',
		),
		'CaseClient' => array(
			'name' => 'case_client_true_name',
			'car_no' => 'case_client_car_no',
			'idno' => 'case_client_idno',
			'traffic_type' => 'case_client_traffic_type',
			'_on' => 'CaseInfo.id=CaseClient.case_id and CaseClient.is_del=0',
			'_type' => 'LEFT',
		),
		'Brigade' => array(
			'name' => 'brigade_name',
			'_table' => '__DEPARTMENT__',
			'_on' => 'Brigade.id=CaseInfo.department_id and Brigade.is_del=0 and Brigade.cate=2',
			'_type' => 'LEFT',
		),
		'PropertyLoss' => array( // 损失类型
			'name' => 'property_loss_name',
			'_table' => '__DICT_OPTION__',
			'_on' => 'CaseInfo.property_loss=PropertyLoss.id',
		),
	);
}
?>