<?php
namespace Admin\Model;
use Think\Model\ViewModel;

class CaseClientDetainViewModel extends ViewModel {
	public $viewFields = array(
		'CaseInfo' => array(
			'id',
			'code',
			'num',
			'cate',
			'accident_name',
			'accident_time',
			'accident_place',
			'lng',
			'lat',
			'death_num',
			'hurt_num',
			'property_loss',
			'accident_type',
			'first_cognizance',
			'department_id',
			'accept_status',
			'accept_check_status',
			'survey_status',
			'client_status',
			'record_status',
			'checkup_status',
			'law_doc_status',
			'cognizance_status',
			'cognizance_check_status',
			'cognizance_send_status',
			'punish_status',
			'punish_complete_status',
			'mediate_status',
			'mediate_complete_status',
			'catalog_status',
			'review_submit_status',
			'review_accept_status',
			'review_result_status',
			'create_time',
			'create_user_id',
			'update_time',
			'update_user_id',
			'is_del',
			'del_reason',
			'is_over',
			'cognizance_type',
			'_table' => '__CASE__',
			'_type' => 'LEFT',
		),
		'CaseClient' => array( // 案件当事人
			'id' => 'case_client_id',
			'name' => 'case_client_true_name',
			'car_no' => 'case_client_car_no',
			'idno' => 'case_client_idno',
			'traffic_type' => 'case_client_traffic_type',
			'is_del' => 'case_client_is_del',
			'_on' => 'CaseInfo.id=CaseClient.case_id and CaseClient.is_del=0',
			'_type' => 'LEFT',
		),
		'CaseClientDetain' => array( // 损失类型
			'id' => 'detain_id',
			'detain_time' => 'detain_time',
			'status' => 'detain_status',
			'name' => 'detain_name',
			'name_id' => 'detain_name_id',
			'is_del' => 'detain_is_del',
			'_on' => 'CaseClient.id=CaseClientDetain.case_client_id',
			'_type' => 'LEFT',
		),
		'CaseHandle' => array( // 当前办案人
			'user_id' => 'case_handle_user_id',
			'start_time' => 'case_handle_start_time',
			'end_time' => 'case_handle_end_time',
			'is_now' => 'case_handle_is_now',
			'is_del' => 'case_handle_is_del',
			'_on' => 'CaseInfo.id=CaseHandle.case_id and CaseHandle.is_now=1 and CaseHandle.is_del=0',
			'_type' => 'LEFT',
		),
		'CaseHandleUser' => array( // 办案人信息
			'user_name' => 'case_handle_user_name',
			'true_name' => 'case_handle_true_name',
			'_table' => '__USER__',
			'_on' => 'CaseHandleUser.id=CaseHandle.user_id and CaseHandleUser.is_del=0',
			'_type' => 'LEFT',
		),
		'Brigade' => array(
			'name' => 'brigade_name',
			'_table' => '__DEPARTMENT__',
			'_on' => 'Brigade.id=CaseInfo.department_id and Brigade.is_del=0 and Brigade.cate=2',
			'_type' => 'LEFT',
		),
		'PropertyLoss' => array( // 损失类型
			'name' => 'property_loss_name',
			'_table' => '__DICT_OPTION__',
			'_on' => 'CaseInfo.property_loss=PropertyLoss.id',
			'_type' => 'LEFT',
		),
		'CaseSurvey' => array(
			'scene_state' => 'case_survey_scene_state',
			'_on' => 'CaseSurvey.case_id=CaseInfo.id',
		),

	);
}
?>