<?php
namespace Admin\Model;
use Think\Model\ViewModel;

class CaseClientViewModel extends ViewModel {
	public $viewFields = array(
		'CaseClient' => array(
			'id',
			'case_id',
			'name',
			'sex',
			'id_type',
			'idno',
			'age',
			'tel',
			'driver_licence_type',
			'first_driver_licence_time',
			'traffic_type',
			'grade_type',
			'car_no',
			'blame_type',
			'hurt_type',
			'death_time',
			'is_escape',
			'escape_catch_man_time',
			'escape_catch_car_time',
			'address',
			'is_checked_breath',
			'breath_val',
			'is_checked_blood',
			'blood_time',
			'is_checked_urine',
			'urine_result',
			'detain_time',
			'detain_parking',
			'detain_force_id',
			'detain_driver_licence',
			'detain_return_time',
			'detain_return_user_id',
			'punish_is_warning',
			'punish_is_fine',
			'punish_money',
			'punish_score',
			'punish_is_seize',
			'punish_seize_time',
			'punish_is_revoke',
			'punish_revoke_time',
			'punish_is_detain',
			'punish_detain_time',
			'criminal_case_type',
			'criminal_measure',
			'create_time',
			'create_user_id',
			'update_time',
			'update_user_id',
			'is_del',
			'_type' => 'LEFT',

		),
		'CaseInfo' => array(
			'code' => 'case_code',
			'num' => 'case_num',
			'cate' => 'case_cate',
			'accident_name' => 'case_accident_name',
			'accident_time' => 'case_accident_time',
			'accident_place' => 'case_accident_place',
			'lng' => 'case_lng',
			'lat' => 'case_lat',
			'death_num' => 'case_death_num',
			'hurt_num' => 'case_hurt_num',
			'property_loss' => 'case_property_loss',
			'accident_type' => 'case_accident_type',
			'first_cognizance' => 'case_first_cognizance',
			'department_id' => 'case_department_id',
			'accept_status' => 'case_accept_status',
			'survey_status' => 'case_survey_status',
			'client_status' => 'case_client_status',
			'record_status' => 'case_record_status',
			'checkup_status' => 'case_checkup_status',
			'law_doc_status' => 'case_law_doc_status',
			'cognizance_status' => 'case_cognizance_status',
			'punish_status' => 'case_punish_status',
			'mediate_status' => 'case_mediate_status',
			'catalog_status' => 'case_catalog_status',
			'create_time' => 'case_create_time',
			'create_user_id' => 'case_create_user_id',
			'update_time' => 'case_update_time',
			'is_del' => 'case_is_del',
			'update_user_id' => 'case_update_user_id',
			'is_over' => 'case_is_over',
			'cognizance_type' => 'case_cognizance_type',
			'_on' => 'CaseClient.case_id=CaseInfo.id',
			'_table' => '__CASE__',
		),
	);
}
?>