<?php
namespace Admin\Model;
use Think\Model\ViewModel;

class CaseCheckupClientViewModel extends ViewModel {
	public $viewFields = array(
		'CaseCheckup' => array(
			'id',
			'case_id',
			'pid',
			'checkup_org_item_pid',
			'checkup_org_item_id',
			'target_case_client_id',
			'target_car_no',
			'target_other',
			'checkup_org_id',
			'finish_time',
			'is_delay',
			'is_out',
			'out_checked',
			'delay_checked',
			'is_cancel',
			'cancel_reason',
			'is_cancel',
			'create_time',
			'create_user_id',
			'update_user_id',
			'is_del',
			'_type' => 'LEFT',
		),
		'CaseClient' => array(
			'id' => 'case_client_id',
			'case_id' => 'case_client_case_id',
			'address' => 'case_client_address',
			'name' => 'case_client_name',
			'sex' => 'case_client_sex',
			'id_type' => 'case_client_id_type',
			'idno' => 'case_client_idno',
			'age' => 'case_client_age',
			'tel' => 'case_client_tel',
			'driver_licence_type' => 'case_client_driver_licence_type',
			'first_driver_licence_time' => 'case_client_first_driver_licence_time',
			'traffic_type' => 'case_client_traffic_type',
			'grade_type' => 'case_client_grade_type',
			'car_no' => 'case_client_car_no',
			'blame_type' => 'case_client_blame_type',
			'hurt_type' => 'case_client_hurt_type',
			'death_time' => 'case_client_death_time',
			'is_escape' => 'case_client_is_escape',
			'escape_catch_man_time' => 'case_client_escape_catch_man_time',
			'escape_catch_car_time' => 'case_client_escape_catch_car_time',
			'is_del' => 'case_client_is_del',
			'_on' => 'CaseClient.id=CaseCheckup.target_case_client_id',
			'_type' => 'LEFT',
		),
		'CheckupOrg' => array(
			'id' => 'checkuporg_id',
			'name' => 'checkuporg_name',
			'status' => 'checkuporg_status',
			'is_end' => 'checkuporg_is_end',
			'create_time' => 'checkuporg_create_time',
			'is_del' => 'checkuporg_is_del',
			'_on' => 'CheckupOrg.id=CaseCheckup.checkup_org_id',
			'_type' => 'LEFT',
		),
		'CheckupOrgItem' => array(
			'id' => 'checkup_org_item_id',
			'name' => 'checkup_org_item_name',
			'_on' => 'CheckupOrgItem.id=CaseCheckup.checkup_org_item_id',
			'_type' => 'LEFT',
		),
	);
}
?>