<?php
namespace Admin\Model;
use Think\Model\ViewModel;

class CaseAlarmViewModel extends ViewModel {
	public $viewFields = array(
		'CaseAlarm' => array(
			'case_id',
			'alarm_id',
			'create_time',
			'create_user_id',
			'_type' => 'LEFT',
		),
		'Alarm' => array(
			'alarm_time' => 'alarm_alarm_time',
			'case_source' => 'alarm_case_source',
			'alarm_name' => 'alarm_alarm_name',
			'contact' => 'alarm_contact',
			'is_protect' => 'alarm_is_protect',
			'accident_time' => 'alarm_accident_time',
			'accident_place' => 'alarm_accident_place',
			'casualties' => 'alarm_casualties',
			'remark' => 'alarm_remark',
			'scene_end_time' => 'alarm_scene_end_time',
			'handle_type' => 'alarm_handle_type',
			'is_link' => 'alarm_is_link',
			'case_id' => 'alarm_case_id',
			'create_time' => 'alarm_create_time',
			'create_user_id' => 'alarm_create_user_id',
			'update_time' => 'alarm_update_time',
			'update_user_id' => 'alarm_update_user_id',
			'is_del' => 'alarm_is_del',
			'del_reason' => 'alarm_del_reason',
			'_on' => 'CaseAlarm.alarm_id=Alarm.id',
			'_type' => 'LEFT',
		),
		'CaseInfo' => array(
			'code' => 'case_code',
			'num' => 'case_num',
			'cate' => 'case_cate',
			'accident_name' => 'case_accident_name',
			'accident_time' => 'case_accident_time',
			'accident_place' => 'case_accident_place',
			'lng' => 'case_lng',
			'lat' => 'case_lat',
			'death_num' => 'case_death_num',
			'hurt_num' => 'case_hurt_num',
			'property_loss' => 'case_property_loss',
			'accident_type' => 'case_accident_type',
			'first_cognizance' => 'case_first_cognizance',
			'department_id' => 'case_department_id',
			'accept_status' => 'case_accept_status',
			'survey_status' => 'case_survey_status',
			'client_status' => 'case_client_status',
			'record_status' => 'case_record_status',
			'checkup_status' => 'case_checkup_status',
			'law_doc_status' => 'case_law_doc_status',
			'cognizance_status' => 'case_cognizance_status',
			'punish_status' => 'case_punish_status',
			'mediate_status' => 'case_mediate_status',
			'catalog_status' => 'case_catalog_status',
			'create_time' => 'case_create_time',
			'create_user_id' => 'case_create_user_id',
			'update_time' => 'case_update_time',
			'update_user_id' => 'case_update_user_id',
			'is_del' => 'case_is_del',
			'del_reason' => 'case_del_reason',
			'is_over' => 'case_is_over',
			'cognizance_type' => 'case_cognizance_type',
			'_table' => '__CASE__',
			'_on' => 'CaseAlarm.case_id=CaseInfo.id',
			'_type' => 'LEFT',
		),
		'AlarmCaseSource' => array(
			'name' => 'alarm_case_source_name',
			'_table' => '__DICT_OPTION__',
			'_on' => 'Alarm.case_source=AlarmCaseSource.id',
		),
	);
}
?>