<?php
namespace Admin\Model;
use Think\Model\ViewModel;

class ArchiveViewModel extends ViewModel {
	public $viewFields = array(
		'Archive' => array(
			'id',
			'case_id',
			'code',
			'name',
			'catalog',
			'dossier',
			'case_no',
			'place',
			'handle',
			'department_id',
			'status',
			'create_time',
			'create_user_id',
			'update_time',
			'update_user_id',
			'is_del',
			'_type' => 'LEFT',
		),
		'CaseInfo' => array(
			'id' => 'case_info_id',
			'code' => 'case_info_code',
			'num' => 'case_info_num',
			'cate' => 'case_info_cate',
			'accident_name' => 'case_info_accident_name',
			'accident_time' => 'case_info_accident_time',
			'accident_place' => 'case_info_accident_place',
			'lng' => 'case_info_lng',
			'lat' => 'case_info_lat',
			'death_num' => 'case_info_death_num',
			'hurt_num' => 'case_info_hurt_num',
			'property_loss' => 'case_info_property_loss',
			'accident_type' => 'case_info_accident_type',
			'first_cognizance' => 'case_info_first_cognizance',
			'department_id' => 'case_info_department_id',
			'accept_status' => 'case_info_accept_status',
			'survey_status' => 'case_info_survey_status',
			'client_status' => 'case_info_client_status',
			'record_status' => 'case_info_record_status',
			'checkup_status' => 'case_info_checkup_status',
			'law_doc_status' => 'case_info_law_doc_status',
			'cognizance_status' => 'case_info_cognizance_status',
			'punish_status' => 'case_info_punish_status',
			'mediate_status' => 'case_info_mediate_status',
			'catalog_status' => 'case_info_catalog_status',
			'create_time' => 'case_info_create_time',
			'create_user_id' => 'case_info_create_user_id',
			'update_time' => 'case_info_update_time',
			'update_user_id' => 'case_info_update_user_id',
			'is_del' => 'case_info_is_del',
			'_table' => '__CASE__',
			'_on' => 'CaseInfo.id=Archive.case_id',
			'_type' => 'LEFT',
		),
		'Department' => array(
			'name' => 'department_name',
			'cate' => 'department_cate',
			'is_del' => 'department_is_del',
			'_on' => 'Archive.department_id=Department.id',
			'_type' => 'LEFT',
		),
		'User' => array(
			'id' => 'user_id',
			'true_name' => 'true_name',
			'user_name' => 'user_name',
			'is_del' => 'user_is_del',
			'_on' => 'Archive.handle=User.id',
		),
	);
}
?>