<?php
namespace Admin\Model;
use Think\Model\ViewModel;

class CaseCheckupEntrustOrgCheckupViewModel extends ViewModel {
	public $viewFields = array(
		'CaseCheckupEntrust' => array(
			'id',
			'case_id',
			'case_checkup_id',
			'code',
			'from_department_id',
			'to_checkup_org_id',
			'to_checkup_org_name',
			'entrust_time',
			'carry_name_1',
			'carry_post_1',
			'carry_idno_1',
			'carry_name_2',
			'carry_post_2',
			'carry_idno_2',
			'carry_address',
			'carry_zip',
			'carry_tel',
			'carry_fax',
			'case_name',
			'case_code',
			'case_name',
			'target_client_id',
			'target_name',
			'target_sex',
			'target_age',
			'target_tel',
			'target_company',
			'target_address',
			'summary',
			'old_result',
			'checkup_doc',
			'remark',
			'is_first',
			'is_submit',
			'is_finish',
			'status',
			'create_time',
			'create_user_id',
			'update_time',
			'update_user_id',
			'is_del',
			'_type' => 'LEFT',
		),
		'CheckupOrg' => array(
			'id' => 'checkuporg_id',
			'name' => 'checkuporg_name',
			'status' => 'checkuporg_status',
			'is_end' => 'checkuporg_is_end',
			'create_time' => 'checkuporg_create_time',
			'is_del' => 'checkuporg_is_del',
			'_on' => 'CheckupOrg.id=CaseCheckupEntrust.to_checkup_org_id',
			'_type' => 'LEFT',
		),
		'CaseInfo' => array(
			'accident_type' => 'case_accident_type',
			'create_time' => 'case_create_time',
			'is_del' => 'case_is_del',
			'_table' => '__CASE__',
			'_on' => 'CaseInfo.id=CaseCheckupEntrust.case_id',
			'_type' => 'LEFT',
		),
		'Department' => array(
			'id' => 'department_id',
			'pid' => 'department_pid',
			'name' => 'department_name',
			'is_del' => 'department_is_del',
			'_on' => 'Department.id=CaseCheckupEntrust.from_department_id',
			'_type' => 'LEFT',
		),
		'CaseCheckup' => array(
			'id' => 'case_checkup_id',
			'checkup_org_item_pid' => 'checkup_org_item_pid',
			'checkup_org_item_id' => 'checkup_org_item_id',
			'finish_time' => 'case_checkup_finish_time',
			'is_del' => 'case_checkup_is_del',
			'is_cancel' => 'case_checkup_is_cancel',
			'_on' => 'CaseCheckup.id=CaseCheckupEntrust.case_checkup_id',
			'_type' => 'LEFT',
		),
		'CheckupOrgItem' => array(
			'id' => 'checkup_org_item_id',
			'name' => 'checkup_org_item_name',
			'is_del' => 'checkup_org_item_id_is_del',
			'_on' => 'CheckupOrgItem.id=CaseCheckup.checkup_org_item_id',
			'_type' => 'LEFT',
		),
	);
}
?>